#!/bin/bash

# Script simplificado para ejecutar SSL manualmente
# Este script te guía paso a paso

DOMAIN="liveweb.website"
SERVER_IP="93.93.116.136"

echo "🔒 Configuración Manual de SSL/HTTPS"
echo "====================================="
echo ""
echo "Este script te guiará para configurar SSL en el servidor."
echo ""
echo "📋 Información:"
echo "   Dominio: ${DOMAIN}"
echo "   Servidor: ${SERVER_IP}"
echo ""
echo "🚀 Ejecuta estos comandos en tu terminal:"
echo ""
echo "1. Conecta al servidor:"
echo "   ssh root@${SERVER_IP}"
echo ""
echo "2. Ve al directorio del proyecto:"
echo "   cd /opt/liveweb"
echo ""
echo "3. Ejecuta el script de SSL:"
echo "   sudo ./infrastructure/scripts/setup-ssl-domain.sh ${DOMAIN}"
echo ""
echo "4. Si el script falla, ejecuta certbot directamente:"
echo "   sudo certbot --nginx -d ${DOMAIN} -d www.${DOMAIN}"
echo ""
echo "5. Verifica que funciona:"
echo "   curl -I https://${DOMAIN}/"
echo ""
echo "📝 Notas:"
echo "   - El script puede pedirte confirmación (presiona Enter)"
echo "   - Certbot necesita que el puerto 80 esté accesible desde internet"
echo "   - DNS debe estar propagado (ya verificamos que está bien)"
echo ""
